"""empty message

Revision ID: 638337824cf2
Revises: b586f16d540d
Create Date: 2023-06-08 10:37:37.632153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '638337824cf2'
down_revision = 'b586f16d540d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tweet', schema=None) as batch_op:
        batch_op.alter_column('datetime',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tweet', schema=None) as batch_op:
        batch_op.alter_column('datetime',
               existing_type=sa.String(length=200),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
