"""empty message

Revision ID: b586f16d540d
Revises: 
Create Date: 2023-06-05 14:48:16.318101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b586f16d540d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preprocess',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('tweet_id', sa.String(length=200), nullable=True),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('text', sa.String(length=2000), nullable=True),
    sa.Column('remove_user', sa.String(length=2000), nullable=True),
    sa.Column('text_cleaning', sa.String(length=2000), nullable=True),
    sa.Column('case_folding', sa.String(length=2000), nullable=True),
    sa.Column('tokenizing', sa.String(length=2000), nullable=True),
    sa.Column('stop_words', sa.String(length=2000), nullable=True),
    sa.Column('stemming', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tweet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('tweet_id', sa.String(length=200), nullable=True),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('text', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tweet')
    op.drop_table('preprocess')
    # ### end Alembic commands ###
