"""empty message

Revision ID: c6d08a0dbee0
Revises: 6d500651d28c
Create Date: 2023-06-12 09:18:05.126863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6d08a0dbee0'
down_revision = '6d500651d28c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labeling',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.String(length=200), nullable=True),
    sa.Column('tweet_id', sa.String(length=200), nullable=True),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('text', sa.String(length=2000), nullable=True),
    sa.Column('remove_user', sa.String(length=2000), nullable=True),
    sa.Column('text_cleaning', sa.String(length=2000), nullable=True),
    sa.Column('case_folding', sa.String(length=2000), nullable=True),
    sa.Column('tokenizing', sa.String(length=2000), nullable=True),
    sa.Column('stop_words', sa.String(length=2000), nullable=True),
    sa.Column('stemming', sa.String(length=2000), nullable=True),
    sa.Column('score', sa.String(length=2000), nullable=True),
    sa.Column('compound', sa.Integer(), nullable=True),
    sa.Column('sentimen', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preprocess',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.String(length=200), nullable=True),
    sa.Column('tweet_id', sa.String(length=200), nullable=True),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('text', sa.String(length=2000), nullable=True),
    sa.Column('remove_user', sa.String(length=2000), nullable=True),
    sa.Column('text_cleaning', sa.String(length=2000), nullable=True),
    sa.Column('case_folding', sa.String(length=2000), nullable=True),
    sa.Column('tokenizing', sa.String(length=2000), nullable=True),
    sa.Column('stop_words', sa.String(length=2000), nullable=True),
    sa.Column('stemming', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tweet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.String(length=200), nullable=True),
    sa.Column('tweet_id', sa.String(length=200), nullable=True),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('text', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tweet')
    op.drop_table('preprocess')
    op.drop_table('labeling')
    # ### end Alembic commands ###
