"""empty message

Revision ID: dd00220102bd
Revises: 6ca2eb05f2b1
Create Date: 2023-06-08 16:45:16.699858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd00220102bd'
down_revision = '6ca2eb05f2b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labeling', schema=None) as batch_op:
        batch_op.alter_column('score',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=2000),
               existing_nullable=True)
        batch_op.alter_column('compound',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labeling', schema=None) as batch_op:
        batch_op.alter_column('compound',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=True)
        batch_op.alter_column('score',
               existing_type=sa.String(length=2000),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
